### ISSUE TITLE
要么你把这个仓库关闭，要么我给这些书籍的出版社举报

### ISSUE THREAD

**Issue by duxiaodou** [crazyandcoder/kindle_free_books#2]
就这么一个充满盗版资源的仓库，竟然还上了**Trending repositories**！

这个仓库中收录的绝大多数书籍，都是拥有版权的。你这样做，侵犯到了书籍作者和出版商的合法权益。

真正开源或者无版权的书籍，可以参考”古登堡计划“。

我个人不是什么圣人，也曾偷偷摸摸或者明目张胆地下载、使用盗版书籍，但这样的做法并不正确。

把其他国家和地区上**Trending repositories**的仓库和我大天朝的相比，我大天朝的大多是”**面试指南**“、”**资源合集**“、”**免费资源**“...... 

很明显，这并不是一件值得骄傲的事情。

我已经向你提出警告，如果你继续坚持分享这些盗版书籍，我将向这些书籍的作者和出版社举报。

**Comment by techeye220** [comment]
我觉得在国内像这样发布kindle书籍的社区太多了。他们和这里的区别就是，这里不用去刷论坛积分之类的。你真要举报的话，应该把所有那些社区一起举报。

另外，我其实觉得出版社不会在意，因为如果他们在意，国内那么多kindle社区早就不会存在了。


> 就这么一个充满盗版资源的仓库，竟然还上了**Trending repositories**！
> 
> 这个仓库中收录的绝大多数书籍，都是拥有版权的。你这样做，侵犯到了书籍作者和出版商的合法权益。
> 
> 真正开源或者无版权的书籍，可以参考”古登堡计划“。
> 
> 我个人不是什么圣人，也曾偷偷摸摸或者明目张胆地下载、使用盗版书籍，但这样的做法并不正确。
> 
> 把其他国家和地区上**Trending repositories**的仓库和我大天朝的相比，我大天朝的大多是”**面试指南**“、”**资源合集**“、”**免费资源**“......
> 
> 很明显，这并不是一件值得骄傲的事情。
> 
> 我已经向你提出警告，如果你继续坚持分享这些盗版书籍，我将向这些书籍的作者和出版社举报。

**Comment by roachsinai** [comment]
同**Trending repositories**点进来。

你讨论版权我觉得和这个repo很相关，而且也必须承认国外很多教材和课程非常好。但是，不要

> 把其他国家和地区上Trending repositories的仓库和我大天朝的相比，我大天朝的大多是”面试指南“、”资源合集“、”免费资源“......

首先**Trending repositories**我没有看到说是和国家相关，然后我看了https://github.com/trending https://github.com/trending/uk https://github.com/trending/us 发现内容完全一致！如果我打开的方式不对，麻烦一定告知，让我好好感受一下高级西方货的不同！

至于，

> 大天朝的大多是”面试指南“、”资源合集“、”免费资源“......

首先还是**Trending repositories**跟你的star有关啊，中国人多（程序员多）是关键，上面这类repo想必更容易star（收藏功能）一下，我觉得这是**Trending repositories**不时出现这些内容的原因。

还有对于此类中国什么的，建议先搜一下英文版的相关内容看看有没有再说是不是中国独有，比如刚才搜了一下 machine learning interview github 也是有的啊。

**Comment by zhuangya** [comment]
`/trending/:lang` 看其他的页面，大概感觉起来是这样噢……

**Comment by csrgxtu** [comment]
本来觉得挺好玩，但是看到 @duxiaodou 这么一说，好像就是这么回事。我们应该遵守知识产权。再说，俗话说：

> 来的容易，去得就容易，就不会珍惜。

**Comment by crazyandcoder** [comment]
我建立这个仓库的初衷是想分享一些我看过的电子书。本人是程序员，不过喜欢看一些历史书籍，找书的过程中也找了很多的提供电子书的网站，就像上面有的伙计说的，需要积分啥的之类的才能下载，而我这里只是统一的整理进行分享出来。**建立这个仓库并没有去获取商业利益，单纯的分享而已**。这里面很多书并没有明确的版本，像古典文学，二十四史等，属于无版本书籍，不过并不排除里面的部分书籍存在版权问题。既然有的读者上纲上线，说是侵权问题，那么欢迎举报，联系原作者。如果有相关的书籍作者联系我，我肯定会第一时间删除相关的侵权书籍。

**Comment by roachsinai** [comment]
@zhuangya 你对比了 https://github.com/trending/:uk 和 https://github.com/trending 结果么？我这里看到的内容是一样的啊。

**Comment by zhuangya** [comment]
@roachsinai 你看这个页面 https://github.com/trending/java 不好奇为啥爪哇岛为啥都只写 java 嘛？

**Comment by roachsinai** [comment]
@zhuangya 说的不是一个东西啊，我说的是国家 https://github.com/trending/cn 你讲的编程语言。

**Comment by msdx** [comment]
https://github.com/wbunle/PersonalShare
这内容如此相似。

**Comment by crazyandcoder** [comment]
@msdx 应该都是在同一个电子书网站上面下载来的。个人感觉不错就分享出来了。
